### PR TITLE
update mapping for Video Playback Completed and add mapping for Video Playback Exited

### PR DESCRIPTION
**Pull request by kdaswani**
**What does this PR do?**
Nielsen has requested we remove any mappings to `end` for DTVR. Instead, Video Playback Completed should be mapped to `stop`.

Additionally, Fox has requested a new event for Video Playback Exited be added to our spec. This has been approved by the spec committee. See here: https://paper.dropbox.com/doc/Video-Spec-Event-Proposal-for-Video-Playback-Exited--A8j5DFZuVoZYlsG~ZQr96tlcAg-rUDm4tQEB1RsdH0R7Xujm. Nielsen has recommended mapping this new event to their `stop` method as well for DTVR.

**Testing**
Unit tests are erroring out with the following message:

```org.mockito.exceptions.base.MockitoException:```
```Mockito cannot mock this class: class com.nielsen.app.sdk.AppSdk.```

Screen Shot 2021-01-28 at 9 17 58 PM

This error happens on the `master` branch as well so I wonder if the Nielsen AppSdk is a private and/or final class. Working on resolving unit tests and testing locally.

Changes being made for iOS and web as well. iOS PR here: https://github.com/segment-integrations/analytics-ios-integration-nielsen-dtvr/pull/12.

### CODE REVIEW

**Comment by kdaswani** [comment]
Hi @mericsson! do you happen to know why I'm getting that mockito error on the unit tests? I tried to run the tests on the master branch as well and received the same error so I believe it's unrelated to the changes I've made. I've updated the Nielsen credentials in my build.gradle. I'll work on testing locally too in case there's just something wrong with the mock in the unit tests.

**Comment by kdaswani** [comment]
closing and re-opening to re-trigger checks

**Comment by kdaswani** [comment]
re-opening to trigger checks with new circle CI

**Comment by kdaswani** [comment]
@prayansh was able to get the unit tests to work!
Screen Shot 2021-03-11 at 5 47 21 PM

**Comment by kdaswani** [comment]
Unit tests passed for me too, including new unit test for `Video Playback Exited`; working on local testing now.

Screen Shot 2021-03-11 at 8 58 19 PM

**Comment by kdaswani** [comment]
Factory unit tests also pass.
Screen Shot 2021-03-12 at 3 52 16 PM

For future reference, steps to make unit tests pass:

- Updated and added dependencies in build.gradle
- Run gradle task `test` (video #1) OR locally change the run configuration by adding `-noverify` (video #2)


https://user-images.githubusercontent.com/49517136/111010549-19e71c00-8354-11eb-957c-fd762fc70451.mov


https://user-images.githubusercontent.com/49517136/111010543-13f13b00-8354-11eb-8872-cabc3bb41131.mov


Note: `-noverify` shouldn't be used in production, but for unit tests this should be a fine exception.

**Review by migs647 — APPROVED** [review]

**Comment by kdaswani** [comment]
Local testing looks good (thanks @prayansh for the help)!

Triggered `Video Content Started` and `Video Playback Completed`. Corresponding Nielsen calls: `PLAY` and `LOADMETADATA` upon content start, `STOP` upon playback complete (this was previously `END`):
Screen Shot 2021-03-19 at 3 04 15 PM

Triggered `Video Content Started` and `Video Playback Exited`. Corresponding Nielsen calls: `PLAY` and `LOADMETADATA` upon content start, `STOP` upon playback exit (this is a net new event with no calls to Nielsen previously):
Screen Shot 2021-03-19 at 3 08 32 PM

I also tested events that are not in our spec, i.e. `Video Playback Exit` (wrong tense) and confirmed no calls were sent to Nielsen. I tested backgrounding the app and `STOP` was called as expected:
Screen Shot 2021-03-19 at 3 09 46 PM

Tested with this source: https://app.segment.com/segment-kiara/sources/new_android_app/debugger

@prayansh @migs647 if this looks good to you, I can either proceed with sharing the .jar with Fox for local testing on their end or a SNAPSHOT if available? Thanks again!

**Comment by kdaswani** [comment]
Snapshot created for Fox testing before we publish a new public version of this integration: `com.segment.analytics.android.integrations:nielsen-dtvr:0.0.3-SNAPSHOT`

The following must be added to the app's build.gradle:
```repositories {
    // add sonatype repository
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
dependencies {
    implementation 'com.segment.analytics.android.integrations:nielsen-dtvr:0.0.3-SNAPSHOT'
}

**Comment by kdaswani** [comment]
Unit tests + CircleCI pass with latest changes:
Screen Shot 2021-03-31 at 12 16 07 PM

**Review by prayansh — APPROVED** [review]
🔥

**Pull request merged**
